const MINI_WINDOW_WIDTH = 300;
const MINI_WINDOW_INITIAL_HEIGHT = 280;
const MINI_WINDOW_MIN_WIDTH = 300;
const MINI_WINDOW_MIN_HEIGHT = 230;
const MINI_WINDOW_MAX_HEIGHT = 420;

module.exports = {
  MINI_WINDOW_WIDTH,
  MINI_WINDOW_INITIAL_HEIGHT,
  MINI_WINDOW_MIN_WIDTH,
  MINI_WINDOW_MIN_HEIGHT,
  MINI_WINDOW_MAX_HEIGHT,
};
